sul-spec:
  name: 'Stanford University Libraries. Special Collections and University Archives'
  visit_note: 'Special Collections and University Archives materials are stored offsite and must be paged 36 hours in advance.'
  description: 'The Special Collections and University Archives Department of Stanford University Libraries is committed to acquiring, preserving, and providing access to primary source materials that support the research needs of the Stanford community and beyond. There are three distinct divisions in our department: Manuscripts, Rare Books and University Archives. We welcome all students, scholars and members of the general public to the Field Reading Room. Learn more about using and accessing our collections.'
  contact_html: |
    <div class="al-repository-contact-phone">(650) 725-1022</div>
    <div class="al-repository-contact-info"><a href="mailto:specialcollections@stanford.edu">specialcollections@stanford.edu</a></div>
  location_html: |
    <div class="al-repository-street-address-building">Green Library</div>
    <div class="al-repository-street-address-address1">557 Escondido Mall</div>
    <div class="al-repository-street-address-city_state_zip_country">Stanford, CA 94305, USA</div>
  thumbnail_url: 'https://library.stanford.edu/sites/default/files/styles/150x150/public/collection/image/Collections-Super-Enlight.jpg'
  request_types: []